ltrace: add patch to fix build on sparc
Due to a missing header inclusion, the build of ltrace of sparc fails
with the following error:

plt.c: In function 'sym2addr':
plt.c:33:12: error: dereferencing pointer to incomplete type
  return sym->enter_addr;
            ^
plt.c:34:1: warning: control reaches end of non-void function [-Wreturn-type]
 }

This commit fixes that by adding a patch to the ltrace code base.

Fixes:

  http://autobuild.buildroot.org/results/55c/55ce618dbe1b2867e5738d90afb2eb67c19200e4/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>