mplayer: add patch due to missing sys/timeb.h
This include file is only available, if uClibc is compiled with
UCLIBC_SUSV3_LEGACY defined and ftime() is not needed in this part of
mplayer at all.

This solves the following compiler error:
win32.c:67:23: error: sys/timeb.h: No such file or directory

Signed-off-by: Markus Heidelberg <markus.heidelberg@web.de>