xapp_xmh: depends on MMU
Fixes http://sysmic.org/~jezz/results/1a0bc183:

command.o: In function `__DoCommandToFileOrPipe':
command.c:(.text+0x35e): undefined reference to `_fork'
collect2: ld returned 1 exit status

Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>