gdb: fixing gdb 7.4.1 build with eglibc-2_16
gdb 7.4.1 fails with the following error
  gdb-7.4.1/gdb/linux-nat.h:79:18: error: field 'siginfo' has incomplete type
because gdb use 'struct siginfo' instead of 'struct siginfo_t'.
Crosstool-NG allready use the patches to prevent this error so use this
patches for buildroot too.

see also http://permalink.gmane.org/gmane.comp.gcc.cross-compiling/15305

Fixes http://autobuild.buildroot.net/results/b894a5cecd9c5e0a1a751ebbff90a14aea1803da/build-end.log

Signed-off-by: Carsten Schoenert <c.schoenert@gmail.com>
Signed-off-by: Peter Korsgaard <jacmet@sunsite.dk>