glog: add dependency on dynamic library
when BR2_STATIC_LIBS=y

src/symbolize.cc:110:19: error: dlfcn.h: No such file or directory

glog requires dlfcn.h header. So add dependency on dynamic library

fixes:
http://autobuild.buildroot.net/results/75d/75d17ceb764c2c1136047c089a0c554770ca98a4/

Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>