libgdiplus: fix cross-compilation error
When cross-compiling with toolchains that validate things like headers
and libraries paths, we were getting errors like:

sh-linux-gnu-gcc: ERROR: unsafe header/library path used in
cross-compilation: '/lib'

That's because there was an error in the configure script that was not
generating ldflags correctly, and the generated Makefile was trying to
link with -L/lib.

Also, it is necessary to pass a prefix when compiling with libjpeg and
libtiff support.

A patch has already been sent upstream.

Fixes:
http://autobuild.buildroot.org/results/58cad610b1bde68de82e44bf3c87d7bfcc1fa816/
http://autobuild.buildroot.org/results/649c258c05293fa5203d7d2c7b20a4265c2815ab/

Signed-off-by: Sergio Prado <sergio.prado@e-labworks.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>