vnstat: add upstream patch to fix build with musl
The header file 'fcntl.h' was missing from 'src/common.h', which caused
the build with musl to fail with undeclared symbol errors like the
following:

  dbaccess.c: In function ‘backupdb’:
  dbaccess.c:268:25: error: ‘O_RDONLY’ undeclared (first use in this function)
    if ((c = open(current, O_RDONLY)) == -1) {
                           ^
This has already been fixed upstream, so the included patch must be
dropped on the next version bump.

Signed-off-by: Rodrigo Rebello <rprebello@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>