libv4l/ir-ctl: fix musl compile
- add copy of TEMP_FAILURE_RETRY macro
- use strdup instead of strdupa

Fixes [1]:

  ir-ctl.c:(.text+0xb06): undefined reference to `strndupa'
  ir-ctl.c:(.text+0xe01): undefined reference to `TEMP_FAILURE_RETRY'

[1] http://autobuild.buildroot.net/results/b8b96c7bbf2147dacac62485cbfdbcfd758271a5

Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>