ltp-testsuite: depends on MMU
Fixes http://sysmic.org/~jezz/results/dfc51d2b:

.../ltp-testsuite-20140115/lib/tests/tst_checkpoint_child.c:40: undefined reference to `_fork'
collect2: ld returned 1 exit status
make[3]: *** [tst_checkpoint_child] Error 1
make[3]: *** Waiting for unfinished jobs....
/tmp/ccF9CQQa.o: In function `main':
.../ltp-testsuite-20140115/lib/tests/tst_checkpoint_parent.c:40: undefined reference to `_fork'
collect2: ld returned 1 exit status
make[3]: *** [tst_checkpoint_parent] Error 1
/tmp/ccwCGpYd.o: In function `main':
.../ltp-testsuite-20140115/lib/tests/tst_checkpoint_parent_exits.c:40: undefined reference to `_fork'
collect2: ld returned 1 exit status
make[3]: *** [tst_checkpoint_parent_exits] Error 1
/tmp/cc8TiB6d.o: In function `main':
.../ltp-testsuite-20140115/lib/tests/tst_process_state.c:43: undefined reference to `_fork'
collect2: ld returned 1 exit status
make[3]: *** [tst_process_state] Error 1
/tmp/ccrf7Gjb.o: In function `main':
.../ltp-testsuite-20140115/lib/tests/tst_checkpoint_child_exits.c:40: undefined reference to `_fork'
collect2: ld returned 1 exit status

[Peter: don't mention mmu dependency in comment]
Signed-off-by: Jérôme Pouiller <jezz@sysmic.org>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>