libglib2: bump version to 2.38.2
libglib2 can fail to build for arm, with the following error.

  gatomic.c:668:2: error: #error G_ATOMIC_LOCK_FREE defined, but incapable of lock-free atomics.

The following upstream commit fixes the problem.

  commit 996edb0c46356d8a326f886b91a77a6af9a2de3e
  Author: Antoine Jacoutot <antoine@mtier.org>
  Date:   Wed Aug 28 09:35:27 2013 +0200

    fix atomic ops detection

    AC_TRY_LINK should be used instead of AC_TRY_COMPILE because the code
    will compile everywhere, either producing ``atomic'' code, or an
    external reference to __sync_bool_compare_and_swap.

    https://bugzilla.gnome.org/show_bug.cgi?id=706958

The upstream commit went into version 2.37.7, so this is the lowest version
that we can bump to, in order to fix the atomic operations problem. However,
2.37.x is a development version, so we bump to 2.38.2 instead.

Signed-off-by: Simon Dawson <spdawson@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>