package/lxc: add patch to fix musl build
Add a patch to fix a build issue with the musl C library.

struct in6_addr is both defined in the C library header <netinet/in.h> and the
Linux kernel header <linux/in6.h>.

lxc_user_nic.c includes both <netinet/in.h> and <linux/if_bridge.h>. The later
one includes <linux/in6.h>.

This breaks build with the musl libc:
  error: redefinition of ‘struct in6_addr’

As lxc_user_nic.c does not use any references from <linux/if_bridge.h> it is
safe to remove this header.

Fixes:
http://autobuild.buildroot.net/results/f32/f321823be6b477be7dc55393e563a3a61794265d/
http://autobuild.buildroot.net/results/8ab/8ab2dc8e0634fbfb582db94cdf94cee5712711f9/
http://autobuild.buildroot.net/results/e27/e27d637b1bb7278ae30d86a72a2d88432d805d2c/
.. and more.

Upstream status: Pending
https://github.com/lxc/lxc/pull/1029

Signed-off-by: Jörg Krause <joerg.krause@embedded.rocks>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>