package/kodi: not available using a musl-based toolchain
The build stops with
configure: error: unsupported host (i586-buildroot-linux-musl)
due to musl not being supported in
https://github.com/xbmc/xbmc/blob/Isengard/m4/xbmc_arch.m4

Removing this obstacle will show that musl is really not being
supported, the build will fail:

In file included from emu_msvcrt.cpp:64:0:
emu_msvcrt.h:93:3: error: ‘__off64_t’ does not name a type
   __off64_t dll_lseeki64(int fd, __off64_t lPos, int iWhence);
   ^
emu_msvcrt.h:94:3: error: ‘__off_t’ does not name a type
   __off_t dll_lseek(int fd, __off_t lPos, int iWhence);
   ^

I know these problems are fixable and the voidlinux projects seems to
have done it already for 15.2-Isengard:
https://github.com/voidlinux/void-packages/tree/99f74705bc6520297d689fae4bcc9606c71ad34f/srcpkgs/kodi/patches

For Jarvis-16.0 these patches have to be rebased at a later stage.
For now block the Kodi package with musl-based toolchains to avoid
build errors.

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>