wayland: fix musl build issue
With musl C library, we see following build failure.

  src/scanner.c: In function 'find_enumeration':
  src/scanner.c:811:2: error: unknown type name 'uint'
    uint idx = 0, j;
    ^

uint is defined in <sys/types.h> header. It is usually included by <stdlib.h>
but in musl stdlib.h doesn't include it.

This patch adds upstream patch where uint32_t is used instead of uint.

Fixes:

  http://autobuild.buildroot.net/results/fcf/fcf6dd3bd31f92eadbcae17338e5887a23e43ff9/

Cc: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Rahul Bedarkar <rahul.bedarkar@imgtec.com>
Acked-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>