trinity: fix typo in MIPS' GET_FP_MODE and SET_FP_MODE macros
Add a patch to fix a typo in the syscalls/prctl.c file. The
PR_GET_FP_MODE and PR_SET_FP_MODE macros are defined in
include/compat.h, but then syscalls/prctl.c tries to use GET_FP_MODE and
SET_FP_MODE. It's lacking the PR_ preffix, and this is causing build
failures like this one:

  CC	syscalls/prctl.o
syscalls/prctl.c:37:2: error: 'GET_FP_MODE' undeclared here (not in a
function)
  GET_FP_MODE, SET_FP_MODE,
  ^
syscalls/prctl.c:37:15: error: 'SET_FP_MODE' undeclared here (not
in a function)
  GET_FP_MODE, SET_FP_MODE,
               ^

This patch has been sent upstream.

Fixes:
  http://autobuild.buildroot.net/results/12f/12f3144b5d99aa1872f6073f3aaac7f8a9c5cfdc/

Signed-off-by: Vicente Olivert Riera <Vincent.Riera@imgtec.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>