riemann-c-client: disable parallel make
Fixes:
http://autobuild.buildroot.net/results/2f8/2f85a2d19232365f7e5fddde6092af9dd74d4518/
http://autobuild.buildroot.net/results/80d/80d83c650c668ee1e87c288bd7a0ce63eab95631/

The build system doesn't specify any dependencies between the generated
header files and the source files including them, causing a race condition:

  GEN      lib/riemann/proto/riemann.pb-c.c
  GEN      lib/riemann/proto/riemann.pb-c.h
  CC       src/src_riemann_client-riemann-client.o
In file included from ./lib/riemann/riemann-client.h:23:0,
                 from src/riemann-client.c:18:
./lib/riemann/attribute.h:21:40: fatal error: riemann/proto/riemann.pb-c.h: No such file or directory

Work around it by forcing non-parallel make.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>