package/wvstreams: disable for musl toolchains
The project seems not maintained anymore since there
is no commit since 2011:
https://github.com/wlach/wvstreams

After fixing the first build issue by adding a missing limit.h header...
xplc/modulemgr.cc:90:14: error: ‘PATH_MAX’ was not declared in this scope
   char fname[PATH_MAX];

and fixing a basename() conflict between the gnu and posix version,
the build fail due to missing __libc_stack_end.

wvtask.cc:(.test+0xb08): undefined reference to `__libc_stack_end'

There is a configure test for __libc_stack_end support but it
doesn't work properly with a musl toolchain.

Since we already have several fixes for uClibc, let's mark wvstreams
as not available for musl toolchains, until someone interested
enough fixes it.

[Thomas: replace uClibc-ng by just uClibc in the Config.in comments.]

Signed-off-by: Romain Naour <romain.naour@openwide.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>