opencv: mark as not available on Xtensa
OpenCV currently does not build on Xtensa due to compiler/assembler
issues:

  Error: operand 2 of 'l32r' has out of range value '4294632228'

Until this gets fixed, let's disable OpenCV on Xtensa.

Temporarily works around:

   http://autobuild.buildroot.net/results/0be/0bed0779685d9ed83466a4d29a0281ca93043a2e/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>