package/iputils: patch ping to link against libm
ping fails to compile with uClibc based toolchains with the error

undefined reference to `__finite'

Add a patch to link ping against libm to resolve the math library function
finite().

Note, this error is not seen with glibc based toolchains because finite
seems to be resolved in both libm and libc.

Fixes:
http://autobuild.buildroot.net/results/08f7386f75c881bc582b338824f8ccd509b2921e/
http://autobuild.buildroot.net/results/5aeef61fbd399dd78dc72b9e7cce978e6f1f58b4/

A pull request has been sent to fix this issue upstream, see
https://github.com/iputils/iputils/pull/42

Signed-off-by: Martin Bark <martin@barkynet.com>
Acked-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>